name: Update Changelog

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: read

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update CHANGELOG.md
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          DATE=$(date -u +"%Y-%m-%d")

          # Initialize file if missing
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

          # ✅ Emoji removed
          NEW_ENTRY="- **${PR_TITLE}** (PR [#${PR_NUMBER}](https://github.com/${{ github.repository }}/pull/${PR_NUMBER})) by @${PR_AUTHOR}"

          # Check if today's section exists
          if grep -q "## ${DATE}" CHANGELOG.md; then
            # Append under today's section
            awk -v date="## ${DATE}" -v entry="$NEW_ENTRY" '
              {
                print $0
                if ($0 == date) {
                  found=1
                } else if (found && $0 !~ /^-/) {
                  print entry
                  found=0
                }
              }
              END {
                if (found) print entry
              }
            ' CHANGELOG.md > CHANGELOG.tmp && mv CHANGELOG.tmp CHANGELOG.md
          else
            # Add new section for today
            {
              echo "## ${DATE}"
              echo "${NEW_ENTRY}"
              echo ""
              cat CHANGELOG.md
            } > CHANGELOG.tmp && mv CHANGELOG.tmp CHANGELOG.md
          fi

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update changelog for PR #${{ github.event.pull_request.number }}"
          git push origin HEAD:${{ github.ref_name }}
